name: bloc_starter
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  intl: ^0.18.1
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  # gen image svg fonts
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # gen locale
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/jpg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
  generate: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/lang # Optional. Directory ARB files. Default: lib/l10n
  output_dir: lib/gen # Optional. Directory Generated localization files. Default: lib/generated

flutter_gen:
  output: lib/gen/ # Optional, default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/colors/colors.xml
